config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs do
    resources :comments
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  get ':id/my_blog' => 'blogs#my_blog', as: :my_blog
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order(updated_at: :desc)
  end

  def my_blog
    @blogs = Blog.where(user_id: current_user.id)
  end
  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:user_id, :title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    @comments = @blog.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @blog.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @blog.comments.new(comment_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to blog_path(@blog, @comment), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @blog.comments.find(params[:id])
    end

    def set_blog
      @blog = Blog.find(params[:blog_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :blog_id, :name, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_blog_comment.html.erb
<hr>
<% c.each do |comment| %>
  <p>
    <strong>Name:</strong>
    <%= comment.name %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <% if current_user.id == comment.user_id %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#edit-comment_<%="#{comment.id}"%>" href="">
      Update your comment
    </button>
    <%= render 'comments/edit_comment_modal', comment: comment, blog: b %>
    <button type="button" class="btn btn-warning">
      <%= link_to 'Destroy', blog_comment_path(b, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    </button>
  <% end %>
  <hr>
<% end %>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <% f.label :body %>
    <%= f.text_area :body, id: "wysiwyg" %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <input type="submit" class="btn btn-primary" id="saveButton" value="Save">
<% end %>

app/views/blogs/_new_comment_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="add-new-comment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for [@blog, Comment.new] do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Leave a Comment</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>

          <div class="field">
            <%= f.label :body %>
            <%= f.text_area :body %>
          </div>

          <div class="field">
            <%= f.hidden_field :blog_id %>
          </div>

          <div class="field">
            <%= f.hidden_field :user_id %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input type="submit" class="btn btn-primary" value="Add Comment">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/_show_blog.html.erb
<div class="container">
  <div class="row">
    <div class="blog-heading">
      <h1><%= b.title.titleize %></h1><br>
      <h4>By <%= b.user.name %></h4>
      <p><%= b.created_at.strftime("%e %b %Y") %><br></p>
    </div>
    <hr>
    <div class="col-md-10 blogShort">
      <article><p>
        <div class="fr-view">
          <%= raw b.body %>
        </div>
      </p></article>
    </div>
    <p>
      <%= b.comments.count %> Comments&nbsp; |
      <% if current_user.id == @blog.user_id %>
        <%= link_to 'Edit', edit_blog_path(b) %>
      <% end %>
    </p>
  </div>
</div>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render 'form', blog: @blog %>
<br>
<%= link_to 'Back', :back %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<button type="button" class="btn btn-info">
  <%= link_to 'New Blog', new_blog_path %>
</button>
<button type="button" class="btn btn-info">
  <%= link_to 'My Blogs', my_blog_path(current_user) %>
</button>
<button type="button" class="btn btn-info">
  <%= link_to 'All Blogs', root_path %>
</button>
<hr>
<div class="wrapper" style="background: #efeff3;">
  <% @blogs.each do |blog| %>
    <div class="top"><div class="title"><h1>Blog</h1></div></div>
    <div class="content">
      <div class="card first">
        <h2>
          <%= link_to blog.title, blog %>
        </h2>
        <p class="date"><%= blog.created_at.strftime("%e %b, %Y") %></p>
        <p class="text">
          <div class="fr-view">
            <%= raw blog.body %>
          </div>
        <br />
        </p>
        <p class="date">By <%= blog.user.name %></p>
        <p class="date"><%= blog.comments.count %> Comments</p>
        <%= link_to 'Show', blog_path(blog) %> |
        <% if current_user.id == blog.user.id %>
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/my_blog.html.erb
<p id="notice"><%= notice %></p>
<button type="button" class="btn btn-info">
  <%= link_to 'New Blog', new_blog_path %>
</button>
<hr>
<div class="wrapper" style="background: #efeff3;">
  <% @blogs.each do |blog| %>
    <div class="top"><div class="title"><h1> My Blog</h1></div></div>
    <div class="content">
      <div class="card first">
        <h2>
          <%= link_to blog.title, blog %>
        </h2>
        <p class="date"><%= blog.created_at.strftime("%e %b, %Y") %></p>
        <p class="text">
          <div class="fr-view">
            <%= raw blog.body %>
          </div>
        <br />
        </p>
        <p class="date">By <%= blog.user.name %></p>
        <p class="date"><%= blog.comments.count %> Comments</p>
        <%= link_to 'Show', blog_path(blog) %> |
        <% if current_user.id == blog.user.id %>
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>
<br>
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'blogs/show_blog', b: @blog %>
<br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-new-comment">
  Leave a comment
</button>
<%= render 'comments/new_comment_modal' %>
<p>
<%= render 'blogs/blog_comment', c: @blog.comments.order(updated_at: :desc), b: @blog %>
</p>
<p>
  <%= link_to 'Back', blogs_path %>
</p>

app/views/comments/_edit_comment_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="edit-comment_<%="#{comment.id}"%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for [blog, comment] do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Update your Comment</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>

          <div class="field">
            <%= f.label :body %>
            <%= f.text_area :body %>
          </div>

          <div class="field">
            <%= f.hidden_field :blog_id %>
          </div>

          <div class="field">
            <%= f.hidden_field :user_id %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input type="submit" class="btn btn-primary" value="Update">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_new_comment_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="add-new-comment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for [@blog, Comment.new] do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Leave a Comment</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>

          <div class="field">
            <%= f.label :body %>
            <%= f.text_area :body %>
          </div>

          <div class="field">
            <%= f.hidden_field :blog_id %>
          </div>

          <div class="field">
            <%= f.hidden_field :user_id %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input type="submit" class="btn btn-primary" value="Add Comment">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,300,700' rel='stylesheet' type='text/css'>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="header-log">
      <% if current_user.present? %>
        <%= current_user.name %><br>
        <button type="button" class="btn btn-warning navbar-btn">
          <%= link_to "Logout",  destroy_user_session_path, method: :delete if user_signed_in? %><br>
        </button>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>